name: todo
description: A simple task app built using flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  animated_text_kit: ^4.2.2
  url_launcher: ^6.1.5
  font_awesome_flutter: ^10.2.1
  flutter_launcher_name: ^0.0.1
  flutter_slidable: ^2.0.0

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_name:
  name: "DewIT"

flutter:

  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: Merriweather
      fonts:
        - asset: fonts/Merriweather-Regular.ttf
    - family: Madi
      fonts:
        - asset: fonts/MsMadi-Regular.ttf
